sudo: required
services:
  - docker

before_install:
  - docker build -t jimweng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jimweng/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-108144349857"
  bucket_path: "docker-react"
  on:
    branch: master
